version: '2.1'

services:
  exclamate-gql:
    build: .
    image: exclamate-gql:0.0.1
    container_name: exclamate-back
    env_file: .env
    volumes:
      - .:/usr/src/app
    networks:
      - exclamate-network
    depends_on:
      - db
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
  db:
    image: mysql:8.0
    container_name: exclamate-db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: exclamate-db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - exclamate-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: exclamate-phpmyadmin
    ports:
      - 8080:80
    networks:
      - exclamate-network
    depends_on:
      - db

networks:
  exclamate-network:
    driver: bridge
